### ISSUE TITLE
Invalid Syntax Error in transpiler.rs during `createNft` call

### ISSUE THREAD

**Issue by movigos** [Turbin3/poseidon#12]
### Problem Description

The code is encountering a syntax issue while trying to match a statement involving an arrow function (ArrowExpr) and a call to the createNft function. The issue occurs in the file `transpiler.rs` at line 48.

### Steps to Reproduce
1. Clone the repository.
2. Navigate to the project directory.
3. Build the project using `cargo build --release`.
4. Run the application and observe the panic.

### Expected Behavior
The code should execute the `createNft` function without causing a syntax error.

### Actual Behavior
The code panics with the following error message:

`thread 'main' panicked at 'Invalid syntax, cannot match: Stmt(Expr(ExprStmt { ... [detailed error output] ... }), is_async: true, is_generator: false, type_params: None, return_type: None }) })), args: [], type_args: None }) }))' note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

### Error Logs

Here is the full error output:

> thread 'main' panicked at 'Invalid syntax, cannot match: 
> Stmt(Expr(ExprStmt {
>   span: Span { lo: BytePos(748), hi: BytePos(1276), ctxt: #0 },
>   expr: Call(CallExpr {
>     span: Span { lo: BytePos(748), hi: BytePos(1275), ctxt: #0 },
>     callee: Expr(Paren(ParenExpr {
>       span: Span { lo: BytePos(748), hi: BytePos(1273), ctxt: #0 },
>       expr: Arrow(ArrowExpr {
>         span: Span { lo: BytePos(749), hi: BytePos(1272), ctxt: #0 },
>         params: [],
>         body: BlockStmt(BlockStmt {
>           span: Span { lo: BytePos(761), hi: BytePos(1272), ctxt: #0 },
>           stmts: [
>             Decl(Var(VarDecl {
>               span: Span { lo: BytePos(767), hi: BytePos(937), ctxt: #0 },
>               kind: "let", declare: false,
>               decls: [VarDeclarator {
>                 span: Span { lo: BytePos(771), hi: BytePos(937), ctxt: #0 },
>                 name: Ident(BindingIdent { id: Ident { span: Span { lo: BytePos(771), hi: BytePos(773), ctxt: #0 }, sym: "tx", optional: false }, type_ann: None }),
>                 init: Some(Await(AwaitExpr {
>                   span: Span { lo: BytePos(775), hi: BytePos(937), ctxt: #0 },
>                   arg: Call(CallExpr {
>                     span: Span { lo: BytePos(781), hi: BytePos(937), ctxt: #0 },
>                     callee: Expr(Ident(Ident { span: Span { lo: BytePos(781), hi: BytePos(790), ctxt: #0 }, sym: "createNft", optional: false })),
>                     args: [
>                       ExprOrSpread { spread: None, expr: Ident(Ident { span: Span { lo: BytePos(791), hi: BytePos(794), ctxt: #0 }, sym: "umi", optional: false }) },
>                       ExprOrSpread {
>                         spread: None,
>                         expr: Object(ObjectLit {
>                           span: Span { lo: BytePos(796), hi: BytePos(936), ctxt: #0 },
>                           props: [
>                             Prop(Shorthand(Ident { span: Span { lo: BytePos(797), hi: BytePos(801), ctxt: #0 }, sym: "mint", optional: false })),
>                             Prop(KeyValue(KeyValueProp {
>                               key: Ident(Ident { span: Span { lo: BytePos(803), hi: BytePos(823), ctxt: #0 }, sym: "sellerFeeBasisPoints", optional: false }),
>                               value: Call(CallExpr {
>                                 span: Span { lo: BytePos(825), hi: BytePos(841), ctxt: #0 },
>                                 callee: Expr(Ident(Ident { span: Span { lo: BytePos(825), hi: BytePos(838), ctxt: #0 }, sym: "percentAmount", optional: false })),
>                                 args: [ExprOrSpread { spread: None, expr: Lit(Num(Number { span: Span { lo: BytePos(839), hi: BytePos(840), ctxt: #0 }, value: 5.0, raw: Some("5") })) }]
>                               })
>                             })),
>                             Prop(KeyValue(KeyValueProp {
>                               key: Ident(Ident { span: Span { lo: BytePos(843), hi: BytePos(847), ctxt: #0 }, sym: "name", optional: false }),
>                               value: Lit(Str(Str { span: Span { lo: BytePos(849), hi: BytePos(858), ctxt: #0 }, value: "IhorRug", raw: Some("\"IhorRug\"") }))
>                             })),
>                             Prop(KeyValue(KeyValueProp {
>                               key: Ident(Ident { span: Span { lo: BytePos(860), hi: BytePos(863), ctxt: #0 }, sym: "uri", optional: false }),
>                               value: Lit(Str(Str { span: Span { lo: BytePos(865), hi: BytePos(935), ctxt: #0 }, value: "https://devnet.irys.xyz/D1gDtpZLRmuVDnkm7B2jGBQKPVrJNkdM5bdBWYV3kPDg", raw: Some("\"https://devnet.irys.xyz/D1gDtpZLRmuVDnkm7B2jGBQKPVrJNkdM5bdBWYV3kPDg\"") }))
>                             }))
>                           ]
>                         })
>                       }
>                     ]
>                   })
>                 }))
>               }]
>             }))
>           ]
>         })
>       })
>     }))
>   }))
>   args: [],
>   type_args: None
> }))'

### Environment
- **OS**: MacOS 15.0.1
- **Rust version**: 1.27.1
- **Branch**: [master](https://github.com/Turbin3/poseidon/tree/master)

**Comment by ShrinathNR** [comment]
hey, can you share your typescript solana program for reference

**Comment by movigos** [comment]
@ShrinathNR 
See here
https://github.com/solana-turbin3/Q4_Sol_Ihor/blob/main/ts/cluster1/nft_mint.ts

**Comment by ShrinathNR** [comment]
The code you have shared does not follow Poseidon syntax. check out our docs and tutorial for the syntax. For now we support limited function in system program and token program.
