### ISSUE TITLE
Struggling to wrap my head around how IDL and the Type folders are created when i run the tests;

### ISSUE THREAD

**Issue by danielAsaboro** [Turbin3/poseidon#18]
Could anyone please do a walk through of how Poseidon converts typescript to rust;
doesn't have to be full fledge and i promise to make it full on documentation once i understand the flow;

everything feels magical and i feel once the magic is unravelled, contributions will flow in

**Comment by ShrinathNR** [comment]
hey, docs has improved a lot and check out the recent blog published by Helius and Turbin3 on Poseidon.

**Comment by danielAsaboro** [comment]
funny enough i started creating a series of tutorial  on poseidon since the weekend, wanna see it?

**Comment by ShrinathNR** [comment]
Sure
