### ISSUE TITLE
TokenProgram does not work 

### ISSUE THREAD

**Issue by adpthegreat** [Turbin3/poseidon#19]
I tried running the escrow as shown in the docs , but it doesn't work , i get so many errors about unsatisfied traits and all 
<img width="995" alt="Screenshot 2024-10-24 at 22 57 11" src="https://github.com/user-attachments/assets/a0682e64-3c85-4d03-87b1-98515a7facaf">
the transpiler does not transpile the code using TokenProgram and Mint properly

**Comment by ShrinathNR** [comment]
[anchor/issues/2745](https://github.com/coral-xyz/anchor/issues/2745)
This is a anchor error, since you're using anchor-spl lib, idl-build needs to be specified in the feature list.

**Comment by adpthegreat** [comment]
okay will try this out
