### ISSUE TITLE
initIfNeeded() doesn't calculate space

### ISSUE THREAD

**Issue by Memewtoo** [Turbin3/poseidon#28]
I tried to convert `.init()` into `.initIfNeeded()`, however to my surprise, when transpiling with `initIfNeeded()` it doesn't calculate the space, though I remember using on another program and it works properly. I'm guessing it's because of the newest types that was pushed some time ago.

Here are the code reference:
```RUST
favorites.derive(["favorites", user.key]).init();
```

Transpiled to:
```RUST
 #[account(
        init,
        payer = user,
        space = 344,
        seeds = [b"favorites",
        user.key().as_ref()],
        bump,
    )]
    pub favorites: Account<'info, FavoritesAccount>,
```

while the one with the `initIfNeeded()`
```RUST
favorites.derive(["favorites", user.key]).initIfNeeded();
```

Results to:
```RUST
#[account(
        init_if_needed,
        payer = user,
        seeds = [b"favorites",
        user.key().as_ref()],
        bump,
    )]
    pub favorites: Account<'info, FavoritesAccount>,
```

As you can notice, it doesn't transpile the space needed for the account.

**Comment by ShrinathNR** [comment]
hey, latest commit has this feature, you can get space constraint while init_if_needed in custom accounts
