### ISSUE TITLE
CLI command poseidon sync only supports double quotation marks

### ISSUE THREAD

**Issue by mwaa** [Turbin3/poseidon#38]
- When you run poseidon sync the regex is looking for program id within double quotation marks `new Pubkey("....")`. This causes the regex to fail where the program id is within single quoation marks `new Pubkey('...')`. This is for the case of [solana program examples ](https://github.com/solana-developers/program-examples) which has a linter that formats to single quotation marks.
- The documentation for the new CLI commands build, test and sync is missing

**Comment by ShrinathNR** [comment]
hey, good observation. this issue is fixed in the latest master branch commit.
