### ISSUE TITLE
Poseidon init does not work properly 

### ISSUE THREAD

**Issue by adpthegreat** [Turbin3/poseidon#40]
So I try to use poseidon init to create a new project ,  if i try to use camelCase , eg `poseidon init myTestProgram`
the anchor init command is called under the hood like so `anchor init myTestProgram` and the converts the name to the kebab case format   as `my-test-program` and creates the anchor project successfully

The problem now is that it fails to create the inner ts-programs folder because it uses the camelCase name for the folder and not the my-test-program folder name,  that is, the actual name of the anchor project so it panics  
![5926750686467442242](https://github.com/user-attachments/assets/c628fef9-8fa7-4130-a807-a653865e3cc5)

**Comment by ShrinathNR** [comment]
hey, this issue is resolved in the latest master branch commit.

**Comment by adpthegreat** [comment]
alright
