### ISSUE TITLE
No support for most SPL functions

### ISSUE THREAD

**Issue by arihantbansal** [Turbin3/poseidon#8]
Functions like `create_metadata_accounts_v3`, and other  SPL functions (for eg, token2022 program and its corresponding functions) present in `anchor-spl` crate are not supported.

This issue is blocking TypeScript program updates for [solana-developers/program-examples](https://github.com/solana-developers/program-examples)

**Comment by mikemaccana** [comment]
Thanks @arihantbansal ! Would you able to compile a list of the most frequently needed SPL functions so we can get them implemented?

**Comment by ShrinathNR** [comment]
Yea sounds like a good idea, we can improve support based on priority.
